#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)
DEFAULT_REPO_PATH=$(cd -- "${SCRIPT_DIR}/../.." && pwd -P)
REPO_PATH=${REPO_PATH:-${DEFAULT_REPO_PATH}}
REPO_PATH=$(cd -- "${REPO_PATH}" && pwd -P)
EMBODIED_PATH=${EMBODIED_PATH:-${REPO_PATH}/examples/embodiment}
CONFIG_NAME=${CONFIG_NAME:-dreamdojo_piper_grpo}
CHECKPOINT_ROOT=${CHECKPOINT_ROOT:-${REPO_PATH}/checkpoints}
PYTHON_BIN=${PYTHON_BIN:-${REPO_PATH}/requirements/dreamdojo-piper/.venv/bin/python}

# Server deployment defaults. Export the same variable before launch to
# override a path without editing this file.
DREAMDOJO_REPO_PATH=${DREAMDOJO_REPO_PATH:-/project/peilab/srk/wmpo_workspace/Dreamdojo}
KAI0_REPO_PATH=${KAI0_REPO_PATH:-/project/peilab/srk/wmpo_workspace/kai0}
PIPER_DATASET_PATH=${PIPER_DATASET_PATH:-/project/peilab/yuyangcheng/dreamdojo-distill/datasets/piper_insert_mouse_battery_lerobot}

STUDENT_CKPT_PATH=${STUDENT_CKPT_PATH:-${CHECKPOINT_ROOT}/dreamdojo_student_distill/iter_000008000}
COSMOS_TOKENIZER_PATH=${COSMOS_TOKENIZER_PATH:-${CHECKPOINT_ROOT}/cosmos-predict2.5-2B/tokenizer.pth}
CR1_EMBEDDINGS_PATH=${CR1_EMBEDDINGS_PATH:-${CHECKPOINT_ROOT}/cosmos-predict2.5-2B/robot/action-cond/cr1_empty_string_text_embeddings.pt}
VLA_CKPT_PATH=${VLA_CKPT_PATH:-${CHECKPOINT_ROOT}/vla_policy/5000}
REWARD_CKPT_PATH=${REWARD_CKPT_PATH:-${CHECKPOINT_ROOT}/reward_model/full_weights.pt}

# Generated by generate_dreamdojo_piper_reset_data.sh. Each episode stores one
# initial camera image and a 36-action demonstration prefix for student warmup.
RESET_DATA_PATH=${RESET_DATA_PATH:-${CHECKPOINT_ROOT}/piper_initial_frames_36}
ACTION_STATS_PATH=${ACTION_STATS_PATH:-${RESET_DATA_PATH}/action_stats.json}

SKIP_PATH_CHECKS=${SKIP_PATH_CHECKS:-0}
SKIP_IMPORT_CHECKS=${SKIP_IMPORT_CHECKS:-0}
APPLY_OPENPI_TRANSFORMERS_OVERLAY=${APPLY_OPENPI_TRANSFORMERS_OVERLAY:-1}
HF_HOME_DIR=${HF_HOME_DIR:-${REPO_PATH}/.cache/huggingface}
DREAMDOJO_DISABLE_SAMPLE_TQDM=${DREAMDOJO_DISABLE_SAMPLE_TQDM:-1}
RLINF_RAY_INCLUDE_DASHBOARD=${RLINF_RAY_INCLUDE_DASHBOARD:-1}
LOG_ROOT=${LOG_ROOT:-${REPO_PATH}/logs}
LOG_DIR=${LOG_DIR:-${LOG_ROOT}/$(date +'%Y%m%d-%H%M%S')-${CONFIG_NAME}}

mkdir -p "${LOG_DIR}" "${HF_HOME_DIR}"
exec > >(tee "${LOG_DIR}/run.log") 2>&1

unset HTTP_PROXY HTTPS_PROXY http_proxy https_proxy ALL_PROXY all_proxy

export HF_HOME="${HF_HOME_DIR}"
export HUGGINGFACE_HUB_CACHE="${HF_HOME_DIR}/hub"
export HF_HUB_OFFLINE=${HF_HUB_OFFLINE:-1}
export REPO_PATH EMBODIED_PATH DREAMDOJO_REPO_PATH KAI0_REPO_PATH
export DREAMDOJO_DISABLE_SAMPLE_TQDM
export RLINF_RAY_INCLUDE_DASHBOARD
export JAX_PLATFORMS=${JAX_PLATFORMS:-cpu}
export PYTORCH_CUDA_ALLOC_CONF=${PYTORCH_CUDA_ALLOC_CONF:-expandable_segments:True}
export PYTHONPATH="${REPO_PATH}/examples/embodiment/compat_site:${KAI0_REPO_PATH}/src:${KAI0_REPO_PATH}/packages/openpi-client/src:${DREAMDOJO_REPO_PATH}/packages/cosmos-cuda:${DREAMDOJO_REPO_PATH}/packages/cosmos-oss:${DREAMDOJO_REPO_PATH}:${REPO_PATH}:${PYTHONPATH:-}"

if [[ "${SKIP_PATH_CHECKS}" != "1" ]]; then
  [[ -x "${PYTHON_BIN}" ]] || {
    echo "Missing uv Python: ${PYTHON_BIN}" >&2
    echo "Run 'uv sync --project requirements/dreamdojo-piper --frozen' in ${REPO_PATH}." >&2
    echo "Alternatively, export PYTHON_BIN for an existing unified environment." >&2
    exit 2
  }
  [[ -d "${DREAMDOJO_REPO_PATH}" ]] || {
    echo "Missing DreamDojo repo: ${DREAMDOJO_REPO_PATH}" >&2
    exit 2
  }
  [[ -d "${KAI0_REPO_PATH}" ]] || {
    echo "Missing OpenPI/kai0 repo: ${KAI0_REPO_PATH}" >&2
    exit 2
  }
  [[ -d "${KAI0_REPO_PATH}/src/openpi/models_pytorch/transformers_replace" ]] || {
    echo "Missing kai0 Transformers overlay under ${KAI0_REPO_PATH}" >&2
    exit 2
  }
  if [[ "${STUDENT_CKPT_PATH}" != s3://* && "${STUDENT_CKPT_PATH}" != msc://* ]]; then
    [[ -f "${STUDENT_CKPT_PATH}/model/.metadata" ]] || {
      echo "Invalid student DCP root: ${STUDENT_CKPT_PATH}/model/.metadata is missing" >&2
      exit 2
    }
  fi
  [[ -d "${VLA_CKPT_PATH}" ]] || {
    echo "Missing VLA checkpoint directory: ${VLA_CKPT_PATH}" >&2
    exit 2
  }
  if [[ -f "${VLA_CKPT_PATH}/model_state_dict/full_weights.pt" || -f "${VLA_CKPT_PATH}/actor/model_state_dict/full_weights.pt" ]]; then
    :
  elif compgen -G "${VLA_CKPT_PATH}/*.safetensors" >/dev/null; then
    :
  else
    echo "Missing VLA weights under ${VLA_CKPT_PATH}; expected full_weights.pt or *.safetensors" >&2
    exit 2
  fi
  [[ -f "${VLA_CKPT_PATH}/assets/norm_stats.json" ]] || {
    echo "Missing OpenPI normalization stats: ${VLA_CKPT_PATH}/assets/norm_stats.json" >&2
    exit 2
  }
  [[ -f "${COSMOS_TOKENIZER_PATH}" ]] || {
    echo "Missing full Cosmos tokenizer checkpoint: ${COSMOS_TOKENIZER_PATH}" >&2
    exit 2
  }
  [[ -f "${CR1_EMBEDDINGS_PATH}" ]] || {
    echo "Missing CR1 embedding cache: ${CR1_EMBEDDINGS_PATH}" >&2
    exit 2
  }
  [[ -f "${REWARD_CKPT_PATH}" ]] || {
    echo "Missing reward checkpoint: ${REWARD_CKPT_PATH}" >&2
    exit 2
  }
  [[ -d "${RESET_DATA_PATH}" ]] || {
    echo "Missing DreamDojo reset data: ${RESET_DATA_PATH}" >&2
    echo "Generate it on the server with:" >&2
    echo "  bash ${EMBODIED_PATH}/generate_dreamdojo_piper_reset_data.sh" >&2
    exit 2
  }
  compgen -G "${RESET_DATA_PATH}/*.npy" >/dev/null || {
    echo "No reset .npy trajectories found in ${RESET_DATA_PATH}" >&2
    exit 2
  }
  [[ -f "${ACTION_STATS_PATH}" ]] || {
    echo "Missing generated action statistics: ${ACTION_STATS_PATH}" >&2
    exit 2
  }
fi

if [[ "${APPLY_OPENPI_TRANSFORMERS_OVERLAY}" == "1" ]]; then
  OPENPI_TRANSFORMERS_OVERLAY=${KAI0_REPO_PATH}/src/openpi/models_pytorch/transformers_replace
  [[ -d "${OPENPI_TRANSFORMERS_OVERLAY}" ]] || {
    echo "Missing OpenPI Transformers overlay: ${OPENPI_TRANSFORMERS_OVERLAY}" >&2
    exit 2
  }
  TRANSFORMERS_PACKAGE_DIR=$("${PYTHON_BIN}" -c \
    'from pathlib import Path; import transformers; print(Path(transformers.__file__).parent)')
  cp -a "${OPENPI_TRANSFORMERS_OVERLAY}/." "${TRANSFORMERS_PACKAGE_DIR}/"
  echo "Applied kai0 Transformers overlay to: ${TRANSFORMERS_PACKAGE_DIR}"
fi

if [[ "${SKIP_IMPORT_CHECKS}" != "1" ]]; then
  "${PYTHON_BIN}" - <<'PY'
import importlib
import sys

from rlinf.envs.world_model.world_model_dreamdojo_env import (
    _patch_omegaconf_resolvers,
)

_patch_omegaconf_resolvers()
required = (
    "torch",
    "ray",
    "cosmos_predict2._src.predict2.interactive.inference.action_video2world",
    "cosmos_predict2._src.predict2.interactive.configs.config_distill",
    "groot_dreams.dataloader",
    "openpi.models_pytorch.pi0_pytorch",
    "openpi.training.config",
    "rlinf.models.embodiment.openpi.dataconfig",
)
failed = []
for name in required:
    try:
        importlib.import_module(name)
    except Exception as error:  # noqa: BLE001 - report native-extension failures too.
        failed.append(f"{name}: {type(error).__name__}: {error}")
if failed:
    raise SystemExit(
        "The selected Python is not the unified DreamDojo/OpenPI runtime:\n  - "
        + "\n  - ".join(failed)
        + "\nRun `uv sync --project requirements/dreamdojo-piper --frozen` "
        "or set PYTHON_BIN to a compatible environment."
    )
print(f"Python runtime: {sys.executable} ({sys.version.split()[0]})")
PY
fi

HYDRA_PATH_OVERRIDES=(
  actor.model.model_path="${VLA_CKPT_PATH}"
  rollout.model.model_path="${VLA_CKPT_PATH}"
  env.train.dreamdojo_repo_path="${DREAMDOJO_REPO_PATH}"
  env.eval.dreamdojo_repo_path="${DREAMDOJO_REPO_PATH}"
  env.train.dreamdojo_ckpt_path="${STUDENT_CKPT_PATH}"
  env.eval.dreamdojo_ckpt_path="${STUDENT_CKPT_PATH}"
  env.train.s3_credential_path="${DREAMDOJO_REPO_PATH}/credentials/s3_checkpoint.secret"
  env.eval.s3_credential_path="${DREAMDOJO_REPO_PATH}/credentials/s3_checkpoint.secret"
  env.train.cosmos_tokenizer_path="${COSMOS_TOKENIZER_PATH}"
  env.eval.cosmos_tokenizer_path="${COSMOS_TOKENIZER_PATH}"
  env.train.cr1_embeddings_path="${CR1_EMBEDDINGS_PATH}"
  env.eval.cr1_embeddings_path="${CR1_EMBEDDINGS_PATH}"
  env.train.reward_model.model_path="${REWARD_CKPT_PATH}"
  env.eval.reward_model.model_path="${REWARD_CKPT_PATH}"
  env.train.initial_image_path="${RESET_DATA_PATH}"
  env.eval.initial_image_path="${RESET_DATA_PATH}"
  env.train.action_norm_stats_path="${ACTION_STATS_PATH}"
  env.eval.action_norm_stats_path="${ACTION_STATS_PATH}"
)

TRAIN_CMD=(
  "${PYTHON_BIN}"
  "${EMBODIED_PATH}/train_embodied_agent.py"
  --config-path "${EMBODIED_PATH}/config"
  --config-name "${CONFIG_NAME}"
  runner.logger.log_path="${LOG_DIR}"
  "${HYDRA_PATH_OVERRIDES[@]}"
  "$@"
)

echo "Using config: ${CONFIG_NAME}"
echo "Using Python: ${PYTHON_BIN}"
echo "DreamDojo repo: ${DREAMDOJO_REPO_PATH}"
echo "kai0 repo: ${KAI0_REPO_PATH}"
echo "Piper dataset: ${PIPER_DATASET_PATH}"
echo "Checkpoint root: ${CHECKPOINT_ROOT}"
echo "Student DCP: ${STUDENT_CKPT_PATH}"
echo "Cosmos tokenizer: ${COSMOS_TOKENIZER_PATH}"
echo "CR1 cache: ${CR1_EMBEDDINGS_PATH}"
echo "VLA checkpoint: ${VLA_CKPT_PATH}"
echo "Reward checkpoint: ${REWARD_CKPT_PATH}"
echo "Reset data: ${RESET_DATA_PATH}"
echo "Action stats: ${ACTION_STATS_PATH}"
echo "Saving full stdout/stderr to: ${LOG_DIR}/run.log"

LAUNCH_JOB_ID=${JOB_ID:-}
if [[ -z "${LAUNCH_JOB_ID}" && -n "${SLURM_JOB_ID:-}" && -z "${SLURM_STEP_ID:-}" ]]; then
  LAUNCH_JOB_ID=${SLURM_JOB_ID}
fi

if [[ -n "${LAUNCH_JOB_ID}" ]]; then
  echo "Launching through srun job ${LAUNCH_JOB_ID}"
  srun --jobid="${LAUNCH_JOB_ID}" --overlap --nodes=1 --ntasks=1 \
    --gres="${GRES:-gpu:8}" --cpus-per-task="${CPUS_PER_TASK:-16}" \
    --export=ALL "${TRAIN_CMD[@]}"
else
  if [[ -n "${CUDA_VISIBLE_DEVICES:-}" && "${CUDA_VISIBLE_DEVICES}" != "NoDevFiles" ]]; then
    VISIBLE_GPU_COUNT=$(awk -F, '{print NF}' <<<"${CUDA_VISIBLE_DEVICES}")
  else
    VISIBLE_GPU_COUNT=$(nvidia-smi -L 2>/dev/null | wc -l || true)
  fi
  VISIBLE_GPU_COUNT=${VISIBLE_GPU_COUNT//[[:space:]]/}
  if [[ "${VISIBLE_GPU_COUNT}" != "8" ]]; then
    echo "Expected exactly 8 visible GPUs, found ${VISIBLE_GPU_COUNT:-0}. Do not run on a login node; enter an 8-GPU Slurm step or set JOB_ID." >&2
    exit 2
  fi
  "${TRAIN_CMD[@]}"
fi
