# Copyright 2026 The RLinf Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""DreamDojo (Cosmos-Predict2 action-conditioned world model) environment.

DreamDojo is NVIDIA's action-conditioned video world model built on
``cosmos_predict2`` (NOT diffsynth). This env wraps the piper post-trained
checkpoint and exposes it through RLinf's :class:`BaseWorldEnv` contract so it
can be driven by an RL policy exactly like ``WanEnv``.

Key piper specifics (see DreamDojo ``configs/2b_1440_640_piper.yaml`` and
``groot_dreams/data/dataset.py``):

* The model consumes a 384-wide action vector per frame; piper's real action
  lives in slots ``[169:183]`` (14 dims = dual-arm joint-position deltas). All
  other slots are zero.
* ``lam_video`` (latent-action embeddings) only modulates slots ``[-32:]`` in
  the *training* forward; for piper those slots are zero, so ``lam_video`` has
  no effect and we pass ``None`` during rollout.
* Generation is image2world autoregressive: condition on the last frame
  (``num_latent_conditional_frames=1``), predict ``chunk`` future frames.

``success_once`` is estimated from the configured reward model using
``success_reward_threshold``. ``terminations`` are still kept independent from
that metric, so training rollout length is controlled by truncation
(``max_episode_steps``).
"""

import io
import json
import os
import sys
from contextlib import nullcontext
from typing import Optional, Union

import numpy as np
import torch
import torch.nn.functional as F

from rlinf.data.datasets.world_model import NpyTrajectoryDatasetWrapper
from rlinf.envs.utils import recursive_to_device
from rlinf.envs.world_model.base_world_env import BaseWorldEnv

__all__ = ["DreamDojoEnv"]


_COSMOS_RESOLVER_PATCHED = False


def _patch_omegaconf_resolvers():
    """Make cosmos's OmegaConf resolver registrations idempotent.

    cosmos_predict2 registers OmegaConf resolvers (``add``/``subtract``/...) at
    import time without ``replace=True``. RLinf already registers a ``subtract``
    resolver, so importing cosmos after rlinf raises ``ValueError: resolver
    'subtract' is already registered``. Patch ``register_new_resolver`` to default
    to ``replace=True`` so cosmos's (semantically compatible, variadic) versions
    win without error. Idempotent.
    """
    global _COSMOS_RESOLVER_PATCHED
    if _COSMOS_RESOLVER_PATCHED:
        return
    from omegaconf import OmegaConf

    _orig = OmegaConf.register_new_resolver

    def _patched(name, resolver, *args, **kwargs):
        kwargs.setdefault("replace", True)
        return _orig(name, resolver, *args, **kwargs)

    OmegaConf.register_new_resolver = _patched
    _COSMOS_RESOLVER_PATCHED = True


class DreamDojoEnv(BaseWorldEnv):
    """RLinf world-model env backed by the DreamDojo piper world model."""

    def __init__(
        self,
        cfg,
        num_envs,
        seed_offset,
        total_num_processes,
        record_metrics=True,
        worker_info=None,
    ):
        super().__init__(
            cfg, num_envs, seed_offset, total_num_processes, worker_info, record_metrics
        )

        # Reset-state management (mirrors WanEnv).
        self.use_fixed_reset_state_ids = cfg.get("use_fixed_reset_state_ids", True)
        self.group_size = cfg.get("group_size", 1)
        self.num_group = self.num_envs // self.group_size

        self._generator = torch.Generator()
        self._generator.manual_seed(self.seed)
        self.update_reset_state_ids()

        # DreamDojo / cosmos generation hyperparameters.
        # `chunk` is the number of 30Hz policy actions consumed per chunk_step
        # (== actor.model.num_action_chunks). The env stride-subsamples them down
        # to `gen_frames` 10fps actions/frames actually generated by the world
        # model (DreamDojo was trained on 30Hz data decimated by action_stride).
        self.chunk = cfg.chunk
        self.action_stride = int(cfg.get("action_stride", 1))
        assert self.chunk % self.action_stride == 0, (
            f"chunk ({self.chunk}) must be divisible by action_stride "
            f"({self.action_stride})"
        )
        self.gen_frames = self.chunk // self.action_stride
        self.num_inference_steps = cfg.get("num_inference_steps", 35)
        self.guidance = cfg.get("guidance", 0)
        self.gen_height = cfg.get("height", 1440)
        self.gen_width = cfg.get("width", 640)
        self.num_latent_conditional_frames = cfg.get(
            "num_latent_conditional_frames", 1
        )
        self.seed_base = self.seed

        # Action layout inside the 384-wide cosmos action vector.
        self.model_action_dim = cfg.get("model_action_dim", 384)
        action_slot = cfg.get("action_slot", [169, 183])
        self.action_slot_start, self.action_slot_end = (
            int(action_slot[0]),
            int(action_slot[1]),
        )
        self.piper_action_dim = self.action_slot_end - self.action_slot_start  # 14
        self.policy_action_format = str(
            cfg.get("policy_action_format", "delta")
        ).lower()
        if self.policy_action_format not in ("delta", "absolute"):
            raise ValueError(
                "policy_action_format must be either 'delta' or 'absolute', "
                f"got {self.policy_action_format!r}"
            )
        self.action_delta_window = int(cfg.get("action_delta_window", 4))
        if self.action_delta_window <= 0:
            raise ValueError(
                f"action_delta_window must be positive, got {self.action_delta_window}"
            )

        # DreamDojo was trained on min-max-normalized *absolute* joint angles that
        # were then differenced (groot_configs.py applies a per-key "min_max"
        # StateActionTransform, and dataset.py builds the grouped delta on top of
        # the normalized sequence). The pi0.5 policy emits absolute joint angles in
        # raw units, so we must reproduce that min-max normalization before the
        # delta -- otherwise the delta is off by a per-joint factor of
        # 2 / (max - min) and the world model receives mis-scaled action
        # conditioning. Load the same stats the dataset used.
        self.action_norm_mode = str(cfg.get("action_norm_mode", "min_max")).lower()
        self.act_norm_min, self.act_norm_max = self._load_action_norm_stats(cfg)

        # Resolution of each per-view image returned to the policy.
        self.image_size = tuple(cfg.image_size)
        # The world model emits the piper cameras vertically stacked
        # (cam_high / cam_left_wrist / cam_right_wrist, top->bottom). Split the
        # generated frame back into this many views before feeding pi0.5:
        # view 0 -> main_images (top_head), views 1.. -> wrist_images stack.
        self.num_camera_views = int(cfg.get("num_camera_views", 1))

        # Build the (persistent) cosmos inference pipeline.
        self.pipe = self._build_pipeline()
        self._negative_prompt = self._default_negative_prompt()

        # Per-frame reward model (RLinf-native ResNet); None -> zero-reward stub.
        self.reward_model = self._load_reward_model()

        # Per-env most-recent RGB frame, uint8 [num_envs, H, W, 3] in [0, 255].
        self.current_obs = None
        # Per-env Piper proprio state. Reset uses dataset state; rollout updates
        # it with the final action of the actual env action chunk.
        self.current_states = None
        self._last_action_state = None
        # All frames generated in the last chunk_step, kept for per-frame reward
        # scoring at native resolution, CHW: uint8 [num_envs, gen_frames, 3, H, W].
        self.last_chunk_frames = None
        self.task_descriptions = [""] * self.num_envs
        self.init_ee_poses = [None] * self.num_envs

        self._is_offloaded = False

    def _record_metrics(self, step_reward, success, infos):
        """Store DreamDojo episode metrics inside the info dict."""
        if not self.record_metrics:
            return infos

        if isinstance(success, torch.Tensor):
            success = success.to(device=self.device, dtype=torch.bool)
        else:
            success = torch.tensor(success, device=self.device, dtype=torch.bool)

        self.success_once = self.success_once | success
        self.returns += step_reward

        episode_len = torch.full(
            (self.num_envs,),
            max(float(self.elapsed_steps), 1.0),
            dtype=torch.float32,
            device=self.device,
        )
        infos["episode"] = {
            "success_once": self.success_once.clone(),
            "return": self.returns.clone(),
            "episode_len": episode_len,
            "reward": self.returns / episode_len,
        }
        return infos

    # ------------------------------------------------------------------
    # Construction helpers
    # ------------------------------------------------------------------
    def _build_dataset(self, cfg):
        # Reuse the same npy initial-frame format as WanEnv. Use the piper
        # converter (convert_piper_to_initial_npy.py) to export LeRobot first
        # frames -> npy. Frames are kept at native resolution; the conditioning
        # frame is resized to (height, width) at rollout time.
        return NpyTrajectoryDatasetWrapper(
            cfg.initial_image_path,
            enable_kir=self.enable_kir,
        )

    def _ensure_dreamdojo_on_path(self):
        """Put the DreamDojo repo on sys.path so cosmos_predict2 is importable."""
        repo_path = self.cfg.get("dreamdojo_repo_path", None)
        if repo_path is not None and repo_path not in sys.path:
            sys.path.insert(0, str(repo_path))
        _patch_omegaconf_resolvers()

    def _build_pipeline(self):
        self._ensure_dreamdojo_on_path()
        from cosmos_predict2._src.predict2.inference.video2world import (
            Video2WorldInference,
        )

        pipe = Video2WorldInference(
            experiment_name=self.cfg.experiment,
            ckpt_path=self.cfg.dreamdojo_ckpt_path,
            s3_credential_path="",
            context_parallel_size=1,
            config_file=self.cfg.config_file,
        )
        return pipe

    def _load_reward_model(self):
        """Build the per-frame reward model from cfg.reward_model.

        Uses the RLinf-native reward registry (e.g. type: "resnet"). Returns
        None when no reward model is configured, in which case the env falls
        back to the zero-reward stub.
        """
        rm_cfg = self.cfg.get("reward_model", None)
        rm_type = rm_cfg.get("type", None) if rm_cfg is not None else None
        if rm_type in (None, "null", ""):
            return None
        from rlinf.models.embodiment.reward import get_reward_model_class

        reward_model = get_reward_model_class(rm_type)(rm_cfg)
        return reward_model.eval().to(self.device)

    def _default_negative_prompt(self):
        self._ensure_dreamdojo_on_path()
        try:
            from cosmos_predict2.config import DEFAULT_NEGATIVE_PROMPT

            return DEFAULT_NEGATIVE_PROMPT
        except Exception:
            return ""

    # ------------------------------------------------------------------
    # Reset-state sampling (same scheme as WanEnv)
    # ------------------------------------------------------------------
    def update_reset_state_ids(self):
        total_num_episodes = len(self.dataset)
        reset_state_ids = torch.randint(
            low=0,
            high=total_num_episodes,
            size=(self.num_group,),
            generator=self._generator,
        )
        self.reset_state_ids = reset_state_ids.repeat_interleave(
            repeats=self.group_size
        ).to(self.device)

    # ------------------------------------------------------------------
    # Reset
    # ------------------------------------------------------------------
    @torch.no_grad()
    def reset(
        self,
        *,
        seed: Optional[Union[int, list[int]]] = None,
        options: Optional[dict] = None,
        episode_indices: Optional[Union[np.ndarray, torch.Tensor]] = None,
    ):
        self.onload()
        self.elapsed_steps = 0

        if self.is_start:
            if self.use_fixed_reset_state_ids:
                episode_indices = self.reset_state_ids
            self._is_start = False

        num_envs = self.num_envs
        if len(self.dataset) < num_envs:
            raise ValueError(
                f"Not enough episodes in dataset. Found {len(self.dataset)}, need {num_envs}"
            )

        if episode_indices is None:
            if seed is not None:
                np.random.seed(seed[0] if isinstance(seed, list) else seed)
            episode_indices = np.random.choice(
                len(self.dataset), size=num_envs, replace=False
            )
        elif isinstance(episode_indices, torch.Tensor):
            episode_indices = episode_indices.cpu().numpy()

        frames = []  # list of uint8 [H, W, 3]
        task_descriptions = []
        init_ee_poses = []

        for episode_idx in episode_indices:
            episode_data = self.dataset[int(episode_idx)]
            if len(episode_data["start_items"]) == 0:
                raise ValueError(f"Empty start_items for episode {episode_idx}")
            first_frame = episode_data["start_items"][0]
            task_descriptions.append(str(episode_data.get("task", "")))

            if "image" not in first_frame:
                raise ValueError(f"No 'image' key in frame for episode {episode_idx}")
            # NpyTrajectoryDatasetWrapper returns CHW float in [0, 1].
            img = first_frame["image"]  # [3, H, W]
            # Resize conditioning frame to native generation resolution.
            if tuple(img.shape[1:]) != (self.gen_height, self.gen_width):
                img = F.interpolate(
                    img.unsqueeze(0),
                    size=(self.gen_height, self.gen_width),
                    mode="bilinear",
                    align_corners=False,
                ).squeeze(0)
            img = (img.clamp(0, 1) * 255.0).to(torch.uint8)  # [3, H, W]
            img = img.permute(1, 2, 0).contiguous()  # [H, W, 3]
            frames.append(img)

            init_ee_poses.append(
                first_frame["observation.state"].numpy()
                if "observation.state" in first_frame
                else None
            )

        # [num_envs, H, W, 3] uint8 on device.
        self.current_obs = torch.stack(frames, dim=0).to(self.device)
        self.task_descriptions = task_descriptions
        self.init_ee_poses = init_ee_poses
        self.current_states = torch.stack(
            [self._format_piper_state(state) for state in init_ee_poses], dim=0
        ).to(self.device)

        self._reset_metrics()
        return self._wrap_obs(), {}

    # ------------------------------------------------------------------
    # Stepping
    # ------------------------------------------------------------------
    def _format_piper_state(self, state):
        if state is None:
            return torch.zeros(self.piper_action_dim, dtype=torch.float32)
        state = torch.as_tensor(state, dtype=torch.float32)
        state = state.flatten()[: self.piper_action_dim]
        if state.numel() < self.piper_action_dim:
            state = F.pad(state, (0, self.piper_action_dim - state.numel()))
        return state

    @torch.no_grad()
    def step(self, actions=None, auto_reset=True):
        raise NotImplementedError(
            "step in DreamDojoEnv is not implemented, use chunk_step instead"
        )

    def _build_model_action(self, env_action):
        """Scatter a piper [chunk, 14] action into a [chunk, 384] cosmos vector."""
        if isinstance(env_action, np.ndarray):
            env_action = torch.from_numpy(env_action)
        env_action = env_action.float()
        chunk = env_action.shape[0]
        model_action = torch.zeros(
            chunk, self.model_action_dim, dtype=torch.float32
        )
        model_action[:, self.action_slot_start : self.action_slot_end] = env_action[
            :, : self.piper_action_dim
        ]
        return model_action

    def _load_action_norm_stats(self, cfg):
        """Load DreamDojo's piper min-max action stats (or None to disable).

        Returns ``(min, max)`` float32 tensors of shape ``[piper_action_dim]`` on
        CPU, matching the per-key ``min_max`` StateActionTransform the DreamDojo
        dataloader applies (``groot_configs.py``). The 14-dim piper action is
        ``[left_arm_joint_position(7), right_arm_joint_position(7)]``; the LeRobot
        ``stats.json`` ``action`` entry stores min/max in exactly that order, so a
        direct slice reproduces the concatenated per-key stats. Returns
        ``(None, None)`` when normalization is disabled.
        """
        if self.action_norm_mode in ("none", "off", "", "null"):
            return None, None
        if self.action_norm_mode != "min_max":
            raise ValueError(
                "action_norm_mode must be 'min_max' or 'none', got "
                f"{self.action_norm_mode!r}"
            )
        stats_path = cfg.get("action_norm_stats_path", None)
        if stats_path in (None, "", "null"):
            raise ValueError(
                "action_norm_mode='min_max' requires 'action_norm_stats_path' "
                "pointing at the DreamDojo piper LeRobot meta/stats.json."
            )
        stats_key = str(cfg.get("action_norm_key", "action"))
        with open(stats_path, "r") as f:
            stats = json.load(f)
        if stats_key not in stats:
            raise KeyError(
                f"'{stats_key}' not found in {stats_path}; available: {list(stats)}"
            )
        entry = stats[stats_key]
        act_min = torch.tensor(entry["min"], dtype=torch.float32)
        act_max = torch.tensor(entry["max"], dtype=torch.float32)
        if act_min.numel() < self.piper_action_dim:
            raise ValueError(
                f"stats '{stats_key}' has {act_min.numel()} dims < piper_action_dim "
                f"{self.piper_action_dim}"
            )
        return (
            act_min[: self.piper_action_dim].contiguous(),
            act_max[: self.piper_action_dim].contiguous(),
        )

    def _normalize_piper_action(self, x):
        """Min-max normalize absolute piper actions into DreamDojo's [-1, 1] space.

        Replicates ``StateActionTransform``'s ``min_max`` branch
        (``groot_dreams/data/transform/state_action.py``): ``2*(x-min)/(max-min)-1``
        for dims with ``min != max`` (0 otherwise), then clamp to ``[-1, 1]``.
        Broadcasts over any leading dims (accepts ``[..., piper_action_dim]``).
        No-op when normalization is disabled.
        """
        if self.act_norm_min is None:
            return x
        mn = self.act_norm_min.to(device=x.device, dtype=x.dtype)
        mx = self.act_norm_max.to(device=x.device, dtype=x.dtype)
        mask = mn != mx
        denom = torch.where(mask, mx - mn, torch.ones_like(mn))
        normed = 2.0 * (x - mn) / denom - 1.0
        normed = torch.where(mask.expand_as(normed), normed, torch.zeros_like(normed))
        return torch.clamp(normed, -1.0, 1.0)

    def _absolute_to_dreamdojo_delta(self, actions):
        """Match DreamDojo's piper delta action construction.

        DreamDojo builds grouped deltas as:
        ``original_outputs["action"][t:t + 4] - original_outputs["action"][t - 1]``
        for ``t = 1, 5, 9, ...``, where ``original_outputs["action"]`` is the
        *min-max-normalized* absolute joint sequence. Here ``actions`` is the
        (raw, absolute) sequence actually fed to DreamDojo; we normalize it (and
        the baseline ``current_states``) exactly like the dataloader before
        differencing. At chunk boundaries, ``current_states`` plays the role of
        ``original_outputs["action"][t - 1]`` for the first group.
        """
        actions = actions.float()
        states = self.current_states
        if states is None:
            states = torch.zeros(
                actions.shape[0],
                self.piper_action_dim,
                dtype=actions.dtype,
                device=actions.device,
            )
        else:
            states = states.detach().to(dtype=actions.dtype, device=actions.device)
            states = states[:, : self.piper_action_dim]
            if states.shape[-1] < self.piper_action_dim:
                states = F.pad(
                    states, (0, self.piper_action_dim - states.shape[-1])
                )

        abs_actions = actions[..., : self.piper_action_dim]
        # Normalize absolute joint angles into DreamDojo's training space *before*
        # differencing (the dataloader normalizes then diffs). The baseline state
        # is part of the same normalized sequence, so normalize it identically.
        abs_actions = self._normalize_piper_action(abs_actions)
        states = self._normalize_piper_action(states)
        delta_actions = torch.empty_like(abs_actions)
        window = self.action_delta_window
        for start in range(0, abs_actions.shape[1], window):
            baseline = states if start == 0 else abs_actions[:, start - 1]
            end = min(start + window, abs_actions.shape[1])
            delta_actions[:, start:end] = abs_actions[:, start:end] - baseline[:, None]
        return delta_actions

    @torch.no_grad()
    def _infer_next_chunk_frames(self, actions):
        """Autoregressively generate the next chunk for each env.

        ``actions`` arrives at 30Hz policy resolution ([num_envs, chunk, 14]);
        we stride-subsample it to the 10fps resolution the world model expects
        ([num_envs, gen_frames, 14]) before generation. All ``gen_frames``
        predicted frames are retained (resized to ``image_size``) in
        ``self.last_chunk_frames`` for per-frame reward scoring, while
        ``self.current_obs`` keeps the last frame at native generation
        resolution to condition the next chunk.
        """
        assert actions.shape[0] == self.num_envs, (
            f"Actions shape {actions.shape} does not match num_envs {self.num_envs}"
        )
        if isinstance(actions, torch.Tensor):
            actions = actions.detach().cpu()
        else:
            actions = torch.from_numpy(np.asarray(actions))

        # 30Hz -> 10fps: keep every action_stride-th action (0, stride, ...).
        actions = actions[:, :: self.action_stride]
        assert actions.shape[1] == self.gen_frames, (
            f"Subsampled action length {actions.shape[1]} != gen_frames "
            f"{self.gen_frames}"
        )
        self._last_action_state = actions[:, -1, : self.piper_action_dim].clone()

        if self.policy_action_format == "absolute":
            actions = self._absolute_to_dreamdojo_delta(actions)

        num_video_frames = self.gen_frames + 1
        new_frames = []  # last frame per env, native res, uint8 [H, W, 3]
        chunk_frames = []  # all predicted frames per env, native CHW uint8 [gen, 3, H, W]

        for env_idx in range(self.num_envs):
            # Build conditioning video: first frame = current obs, rest zeros.
            last_frame = self.current_obs[env_idx]  # [H, W, 3] uint8
            img = last_frame.permute(2, 0, 1).unsqueeze(0).float()  # [1, 3, H, W]
            vid_input = torch.cat(
                [img, torch.zeros_like(img).repeat(num_video_frames - 1, 1, 1, 1)],
                dim=0,
            )  # [T, 3, H, W]
            vid_input = (
                vid_input.to(torch.uint8).unsqueeze(0).permute(0, 2, 1, 3, 4)
            )  # [1, 3, T, H, W]

            model_action = self._build_model_action(actions[env_idx])

            video = self.pipe.generate_vid2world(
                prompt="",
                input_path=vid_input,
                action=model_action,
                guidance=self.guidance,
                num_video_frames=num_video_frames,
                num_latent_conditional_frames=self.num_latent_conditional_frames,
                resolution="none",
                seed=self.seed_base + self.elapsed_steps + env_idx,
                negative_prompt=self._negative_prompt,
                num_steps=self.num_inference_steps,
                lam_video=None,
            )
            # video: [1, 3, T, H, W] in [-1, 1]. Frame 0 is the conditioning
            # frame; frames [1:] are the gen_frames predictions.
            video = (video + 1.0) / 2.0
            pred = torch.clamp(video[0, :, 1:], 0, 1)  # [3, gen, H, W] in [0, 1]

            # Last predicted frame, native res, for next-step conditioning + obs.
            last = (pred[:, -1] * 255.0).to(torch.uint8)  # [3, H, W]
            new_frames.append(last.permute(1, 2, 0).contiguous())  # [H, W, 3]

            # All predicted frames at native resolution, CHW, for reward scoring
            # (the reward model consumes [3, H, W] without any resize).
            frames_native = (pred * 255.0).to(torch.uint8)  # [3, gen, H, W]
            chunk_frames.append(
                frames_native.permute(1, 0, 2, 3).contiguous()
            )  # [gen, 3, H, W]

            del video
            self._clear_accelerator_cache()

        self.current_obs = torch.stack(new_frames, dim=0).to(self.device)
        self.last_chunk_frames = torch.stack(chunk_frames, dim=0).to(self.device)

    @torch.no_grad()
    def _infer_next_chunk_rewards(self):
        """Per-frame reward via the ResNet reward model.

        Scores each of the ``gen_frames`` (10fps) frames generated in the last
        chunk_step, then ``repeat_interleave(action_stride)`` broadcasts each
        frame's reward back onto its ``action_stride`` underlying 30Hz actions,
        yielding shape [num_envs, chunk]. Falls back to zeros when no reward
        model is configured.
        """
        if self.reward_model is None or self.last_chunk_frames is None:
            return torch.zeros(
                self.num_envs, self.chunk, dtype=torch.float32, device=self.device
            )

        # last_chunk_frames: [N, gen, 3, H, W] uint8 at native resolution. Score
        # one 10fps frame index at a time (batch == num_envs) to keep the native
        # full-res ResNet forward within memory.
        per_frame = []
        for i in range(self.gen_frames):
            imgs = self.last_chunk_frames[:, i]  # [N, 3, H, W]
            r = self.reward_model.compute_reward({"main_images": imgs})  # [N]
            per_frame.append(r.reshape(self.num_envs))
        rewards = torch.stack(per_frame, dim=1).to(
            dtype=torch.float32, device=self.device
        )  # [N, gen]
        # [N, gen] -> [N, chunk]: frame i covers actions [i*stride : (i+1)*stride].
        return rewards.repeat_interleave(self.action_stride, dim=1)

    def _calc_step_reward(self, chunk_rewards):
        if self.use_rel_reward:
            reward_diffs = torch.zeros(
                (self.num_envs, self.chunk), dtype=torch.float32, device=self.device
            )
            for i in range(self.chunk):
                reward_diffs[:, i] = (
                    self.cfg.get("reward_coef", 1.0) * chunk_rewards[:, i]
                    - self.prev_step_reward
                )
                self.prev_step_reward = (
                    self.cfg.get("reward_coef", 1.0) * chunk_rewards[:, i]
                )
            return reward_diffs
        return chunk_rewards

    def _resize_to_policy(self, image):
        """Resize [N, H, W, 3] uint8 to the policy's per-view image_size."""
        if tuple(image.shape[1:3]) == self.image_size:
            return image
        x = image.permute(0, 3, 1, 2).float()  # [N, 3, H, W]
        x = F.interpolate(
            x, size=self.image_size, mode="bilinear", align_corners=False
        )
        return x.permute(0, 2, 3, 1).clamp(0, 255).to(torch.uint8)

    def get_video_frame_batches(self):
        """Return native generated chunk frames as [time][env] RGB arrays."""
        if self.last_chunk_frames is None:
            return []
        frames = self.last_chunk_frames.detach().cpu().numpy()
        # [N, gen, 3, H, W] -> [gen][N][H, W, 3].
        return [
            [frames[env_idx, t].transpose(1, 2, 0) for env_idx in range(self.num_envs)]
            for t in range(frames.shape[1])
        ]

    def _wrap_obs(self):
        """Return obs dict aligned with libero_env / WanEnv format.

        The world model emits the piper cameras vertically stacked into a single
        [num_envs, H, W, 3] frame. Split it into ``num_camera_views`` views:
        view 0 -> main_images (top_head), the rest -> wrist_images stacked as
        [num_envs, num_views-1, h, w, 3] (AgilexInputs maps the 2-stack to
        hand_left / hand_right). With num_camera_views == 1 this degrades to the
        old single-image behavior.
        """
        full_image = self.current_obs  # [num_envs, H, W, 3] uint8
        n_views = self.num_camera_views

        if n_views > 1:
            height = full_image.shape[1]
            assert height % n_views == 0, (
                f"generated height {height} not divisible by num_camera_views "
                f"{n_views}"
            )
            vh = height // n_views
            views = [
                self._resize_to_policy(full_image[:, i * vh : (i + 1) * vh])
                for i in range(n_views)
            ]
            main_images = views[0]
            wrist_images = torch.stack(views[1:], dim=1)  # [N, n_views-1, h, w, 3]
        else:
            main_images = self._resize_to_policy(full_image)
            wrist_images = None

        states = self.current_states
        if states is None:
            states = torch.zeros(
                (self.num_envs, self.piper_action_dim),
                device=self.device,
                dtype=torch.float32,
            )
        return {
            "main_images": main_images,
            "wrist_images": wrist_images,
            "extra_view_images": None,
            "states": states,
            "task_descriptions": self.task_descriptions,
        }

    def _handle_auto_reset(self, dones, extracted_obs, infos):
        final_obs = extracted_obs
        final_info = infos
        extracted_obs, infos = self.reset()
        infos["final_observation"] = final_obs
        infos["final_info"] = final_info
        infos["_final_info"] = dones
        infos["_final_observation"] = dones
        infos["_elapsed_steps"] = dones
        return extracted_obs, infos

    @torch.no_grad()
    def chunk_step(self, policy_output_action):
        """Advance one chunk. ``policy_output_action``: [num_envs, chunk, 14]."""
        self.onload()
        if policy_output_action.shape[0] != self.num_envs:
            raise ValueError(
                f"Action batch {policy_output_action.shape[0]} != num_envs "
                f"{self.num_envs}"
            )
        if policy_output_action.shape[1] <= 0:
            raise ValueError("Action chunk must contain at least one action.")
        autocast_context = (
            torch.amp.autocast(device_type=self.device.type, dtype=torch.bfloat16)
            if self.device.type != "cpu"
            else nullcontext()
        )
        with autocast_context:
            self._infer_next_chunk_frames(policy_output_action)

        self.elapsed_steps += self.chunk
        last_actions = (
            self._last_action_state
            if self._last_action_state is not None
            else torch.as_tensor(policy_output_action[:, -1, :], dtype=torch.float32)
        )
        last_actions = last_actions[:, : self.piper_action_dim]
        if last_actions.shape[-1] < self.piper_action_dim:
            last_actions = F.pad(
                last_actions, (0, self.piper_action_dim - last_actions.shape[-1])
            )
        self.current_states = last_actions.to(device=self.device)
        extracted_obs = self._wrap_obs()

        chunk_rewards = self._infer_next_chunk_rewards()
        chunk_rewards_tensors = self._calc_step_reward(chunk_rewards)
        success_threshold = float(self.cfg.get("success_reward_threshold", 0.9))
        chunk_success = chunk_rewards.max(dim=1).values >= success_threshold

        # Reward model not available -> no success detection; terminate only on
        # truncation (max_episode_steps).
        raw_chunk_terminations = torch.zeros(
            self.num_envs, self.chunk, dtype=torch.bool, device=self.device
        )
        raw_chunk_truncations = torch.zeros(
            self.num_envs, self.chunk, dtype=torch.bool, device=self.device
        )
        truncations = torch.tensor(
            self.elapsed_steps >= self.cfg.max_episode_steps, device=self.device
        )
        if truncations.any():
            raw_chunk_truncations[:, -1] = truncations

        past_terminations = raw_chunk_terminations.any(dim=1)
        past_truncations = raw_chunk_truncations.any(dim=1)
        past_dones = torch.logical_or(past_terminations, past_truncations)

        if past_dones.any() and self.auto_reset:
            extracted_obs, infos = self._handle_auto_reset(past_dones, extracted_obs, {})
        else:
            infos = {}

        infos = self._record_metrics(
            chunk_rewards_tensors.sum(dim=1), chunk_success, infos
        )

        chunk_terminations = torch.zeros_like(raw_chunk_terminations)
        chunk_terminations[:, -1] = past_terminations
        chunk_truncations = torch.zeros_like(raw_chunk_truncations)
        chunk_truncations[:, -1] = past_truncations

        return (
            [extracted_obs],
            chunk_rewards_tensors,
            chunk_terminations,
            chunk_truncations,
            [infos],
        )

    # ------------------------------------------------------------------
    # Offload / state (for RLinf memory management)
    # ------------------------------------------------------------------
    def _move_pipe(self, device):
        for attr in ("dit", "net", "model", "vae", "tokenizer", "text_encoder"):
            module = getattr(self.pipe, attr, None)
            if module is not None and hasattr(module, "to"):
                try:
                    setattr(self.pipe, attr, module.to(device))
                except Exception:
                    pass

    def offload(self):
        if self._is_offloaded:
            return
        self._move_pipe("cpu")
        if self.reward_model is not None:
            self.reward_model = self.reward_model.to("cpu")
        if self.current_obs is not None:
            self.current_obs = recursive_to_device(self.current_obs, "cpu")
        if self.current_states is not None:
            self.current_states = recursive_to_device(self.current_states, "cpu")
        if self.last_chunk_frames is not None:
            self.last_chunk_frames = recursive_to_device(self.last_chunk_frames, "cpu")
        self.prev_step_reward = self.prev_step_reward.cpu()
        self.reset_state_ids = self.reset_state_ids.cpu()
        if self.record_metrics:
            self.success_once = self.success_once.cpu()
            self.returns = self.returns.cpu()
        self._clear_accelerator_cache()
        self._is_offloaded = True

    def onload(self):
        if not self._is_offloaded:
            return
        self._move_pipe(self.device)
        if self.reward_model is not None:
            self.reward_model = self.reward_model.to(self.device)
        if self.current_obs is not None:
            self.current_obs = recursive_to_device(self.current_obs, self.device)
        if self.current_states is not None:
            self.current_states = recursive_to_device(self.current_states, self.device)
        if self.last_chunk_frames is not None:
            self.last_chunk_frames = recursive_to_device(
                self.last_chunk_frames, self.device
            )
        self.prev_step_reward = self.prev_step_reward.to(self.device)
        self.reset_state_ids = self.reset_state_ids.to(self.device)
        if self.record_metrics:
            self.success_once = self.success_once.to(self.device)
            self.returns = self.returns.to(self.device)
        self._is_offloaded = False

    def get_state(self) -> bytes:
        env_state = {
            "current_obs": recursive_to_device(self.current_obs, "cpu")
            if self.current_obs is not None
            else None,
            "current_states": recursive_to_device(self.current_states, "cpu")
            if self.current_states is not None
            else None,
            "task_descriptions": self.task_descriptions,
            "init_ee_poses": self.init_ee_poses,
            "elapsed_steps": self.elapsed_steps,
            "prev_step_reward": self.prev_step_reward.cpu(),
            "_is_start": self._is_start,
            "reset_state_ids": self.reset_state_ids.cpu(),
            "generator_state": self._generator.get_state(),
        }
        if self.record_metrics:
            env_state.update(
                {
                    "success_once": self.success_once.cpu(),
                    "returns": self.returns.cpu(),
                }
            )
        buffer = io.BytesIO()
        torch.save(env_state, buffer)
        return buffer.getvalue()


if __name__ == "__main__":
    from pathlib import Path

    from hydra import compose
    from hydra.core.global_hydra import GlobalHydra
    from hydra.initialize import initialize_config_dir

    os.environ.setdefault("EMBODIED_PATH", "examples/embodiment")
    repo_root = Path(__file__).resolve().parents[3]
    GlobalHydra.instance().clear()
    config_dir = Path(
        os.environ.get("EMBODIED_CONFIG_DIR", repo_root / "examples/embodiment/config")
    ).resolve()
    config_name = os.environ.get("DREAMDOJO_CONFIG", "dreamdojo_piper_grpo")

    print(f"Loading config: {config_name} from {config_dir}")
    with initialize_config_dir(config_dir=str(config_dir), version_base="1.1"):
        cfg_ = compose(config_name=config_name)
        cfg = cfg_["env"]["train"]

    env = DreamDojoEnv(cfg, cfg.total_num_envs, seed_offset=0, total_num_processes=1)
    obs, info = env.reset()
    print("After reset, obs keys:", list(obs.keys()))
    print("main_images:", obs["main_images"].shape, obs["main_images"].dtype)

    zeros_actions = np.zeros((cfg.total_num_envs, cfg.chunk, 14), dtype=np.float32)
    o, r, te, tr, infos = env.chunk_step(zeros_actions)
    print("After chunk_step:", o[0]["main_images"].shape, "reward", r.shape)
